apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: 224574/todoapp:tagname
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db-pv
              mountPath: /app/data
      volumes:
        - name: db-pv
          persistentVolumeClaim:
            claimName: db-pvc